### ISSUE TITLE
Add Hubspace product

### ISSUE THREAD

**Issue by Hirez24** [XenuIsWatching/homebridge-hubspace#1]
Request for adding Defiant Smart Lock (HSGCDX2D01APPB) this lock is addressed over bluetooth from a Defiant smart Plug which is connected to wifi, I can control both product from the hub space app but the lock is tied to the plug for communication. 

Let me know if this is possible, not a coder myself but willing to learn and  am willing to provide any information necessary so long as I have proper instruction. 

Thanks for creating this ion the first place.

**Comment by XenuIsWatching** [comment]
Not possible
